/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lsp8CollecLsp7Sol from "./LSP8CollecLSP7.sol";
export type { lsp8CollecLsp7Sol };
export type { BasicLSP8 } from "./BasicLSP8";
export type { LSP7SubCollection } from "./LSP7SubCollection";
export type { LSP8CollectionOfCollections } from "./LSP8CollectionOfCollections";
export type { LSP8ParentCollection } from "./LSP8ParentCollection";
export type { LSP8Proxy } from "./LSP8Proxy";
export type { LSP8SubCollection } from "./LSP8SubCollection";
