/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lsp8CollecLp7Sol from "./LSP8CollecLP7.sol";
export type { lsp8CollecLp7Sol };
import type * as lsp8CollecLsp7Sol from "./LSP8CollecLSP7.sol";
export type { lsp8CollecLsp7Sol };
import type * as lsp8CollecOfCollecSol from "./LSP8CollecOfCollec.sol";
export type { lsp8CollecOfCollecSol };
export type { BasicLSP8 } from "./BasicLSP8";
export type { LSP7SubCollection } from "./LSP7SubCollection";
export type { LSP8Proxy } from "./LSP8Proxy";
