/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as presets from "./presets";
export type { presets };
export type { ILSP8IdentifiableDigitalAsset } from "./ILSP8IdentifiableDigitalAsset";
export type { LSP8IdentifiableDigitalAsset } from "./LSP8IdentifiableDigitalAsset";
export type { LSP8IdentifiableDigitalAssetCore } from "./LSP8IdentifiableDigitalAssetCore";
