/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "OwnableUnset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OwnableUnset__factory>;
    getContractFactory(
      name: "ERC725Y",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC725Y__factory>;
    getContractFactory(
      name: "ERC725YCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC725YCore__factory>;
    getContractFactory(
      name: "IERC725Y",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC725Y__factory>;
    getContractFactory(
      name: "LSP17Extendable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP17Extendable__factory>;
    getContractFactory(
      name: "ILSP1UniversalReceiver",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP1UniversalReceiver__factory>;
    getContractFactory(
      name: "LSP4DigitalAssetMetadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP4DigitalAssetMetadata__factory>;
    getContractFactory(
      name: "LSP4DigitalAssetMetadataCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP4DigitalAssetMetadataCore__factory>;
    getContractFactory(
      name: "ILSP7DigitalAsset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP7DigitalAsset__factory>;
    getContractFactory(
      name: "LSP7DigitalAsset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP7DigitalAsset__factory>;
    getContractFactory(
      name: "LSP7DigitalAssetCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP7DigitalAssetCore__factory>;
    getContractFactory(
      name: "ILSP8IdentifiableDigitalAsset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP8IdentifiableDigitalAsset__factory>;
    getContractFactory(
      name: "LSP8IdentifiableDigitalAsset",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP8IdentifiableDigitalAsset__factory>;
    getContractFactory(
      name: "LSP8IdentifiableDigitalAssetCore",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP8IdentifiableDigitalAssetCore__factory>;
    getContractFactory(
      name: "ILSP8Mintable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ILSP8Mintable__factory>;
    getContractFactory(
      name: "LSP8Mintable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP8Mintable__factory>;
    getContractFactory(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC165__factory>;
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "BasicLSP8",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasicLSP8__factory>;
    getContractFactory(
      name: "BasicLSP8CollectionOfCollections",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasicLSP8CollectionOfCollections__factory>;
    getContractFactory(
      name: "LSP7SubCollection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP7SubCollection__factory>;
    getContractFactory(
      name: "LSP8Collection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP8Collection__factory>;
    getContractFactory(
      name: "BasicLSP8Collection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.BasicLSP8Collection__factory>;
    getContractFactory(
      name: "LSP8Proxy",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LSP8Proxy__factory>;

    getContractAt(
      name: "OwnableUnset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OwnableUnset>;
    getContractAt(
      name: "ERC725Y",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC725Y>;
    getContractAt(
      name: "ERC725YCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC725YCore>;
    getContractAt(
      name: "IERC725Y",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC725Y>;
    getContractAt(
      name: "LSP17Extendable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP17Extendable>;
    getContractAt(
      name: "ILSP1UniversalReceiver",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP1UniversalReceiver>;
    getContractAt(
      name: "LSP4DigitalAssetMetadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP4DigitalAssetMetadata>;
    getContractAt(
      name: "LSP4DigitalAssetMetadataCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP4DigitalAssetMetadataCore>;
    getContractAt(
      name: "ILSP7DigitalAsset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP7DigitalAsset>;
    getContractAt(
      name: "LSP7DigitalAsset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP7DigitalAsset>;
    getContractAt(
      name: "LSP7DigitalAssetCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP7DigitalAssetCore>;
    getContractAt(
      name: "ILSP8IdentifiableDigitalAsset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP8IdentifiableDigitalAsset>;
    getContractAt(
      name: "LSP8IdentifiableDigitalAsset",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP8IdentifiableDigitalAsset>;
    getContractAt(
      name: "LSP8IdentifiableDigitalAssetCore",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP8IdentifiableDigitalAssetCore>;
    getContractAt(
      name: "ILSP8Mintable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ILSP8Mintable>;
    getContractAt(
      name: "LSP8Mintable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP8Mintable>;
    getContractAt(
      name: "ERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC165>;
    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "BasicLSP8",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BasicLSP8>;
    getContractAt(
      name: "BasicLSP8CollectionOfCollections",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BasicLSP8CollectionOfCollections>;
    getContractAt(
      name: "LSP7SubCollection",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP7SubCollection>;
    getContractAt(
      name: "LSP8Collection",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP8Collection>;
    getContractAt(
      name: "BasicLSP8Collection",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.BasicLSP8Collection>;
    getContractAt(
      name: "LSP8Proxy",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LSP8Proxy>;

    deployContract(
      name: "OwnableUnset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUnset>;
    deployContract(
      name: "ERC725Y",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725Y>;
    deployContract(
      name: "ERC725YCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725YCore>;
    deployContract(
      name: "IERC725Y",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC725Y>;
    deployContract(
      name: "LSP17Extendable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP17Extendable>;
    deployContract(
      name: "ILSP1UniversalReceiver",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP1UniversalReceiver>;
    deployContract(
      name: "LSP4DigitalAssetMetadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP4DigitalAssetMetadata>;
    deployContract(
      name: "LSP4DigitalAssetMetadataCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP4DigitalAssetMetadataCore>;
    deployContract(
      name: "ILSP7DigitalAsset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP7DigitalAsset>;
    deployContract(
      name: "LSP7DigitalAsset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP7DigitalAsset>;
    deployContract(
      name: "LSP7DigitalAssetCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP7DigitalAssetCore>;
    deployContract(
      name: "ILSP8IdentifiableDigitalAsset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP8IdentifiableDigitalAsset>;
    deployContract(
      name: "LSP8IdentifiableDigitalAsset",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8IdentifiableDigitalAsset>;
    deployContract(
      name: "LSP8IdentifiableDigitalAssetCore",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8IdentifiableDigitalAssetCore>;
    deployContract(
      name: "ILSP8Mintable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP8Mintable>;
    deployContract(
      name: "LSP8Mintable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8Mintable>;
    deployContract(
      name: "ERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "BasicLSP8",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasicLSP8>;
    deployContract(
      name: "BasicLSP8CollectionOfCollections",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasicLSP8CollectionOfCollections>;
    deployContract(
      name: "LSP7SubCollection",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP7SubCollection>;
    deployContract(
      name: "LSP8Collection",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8Collection>;
    deployContract(
      name: "BasicLSP8Collection",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasicLSP8Collection>;
    deployContract(
      name: "LSP8Proxy",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8Proxy>;

    deployContract(
      name: "OwnableUnset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OwnableUnset>;
    deployContract(
      name: "ERC725Y",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725Y>;
    deployContract(
      name: "ERC725YCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC725YCore>;
    deployContract(
      name: "IERC725Y",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC725Y>;
    deployContract(
      name: "LSP17Extendable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP17Extendable>;
    deployContract(
      name: "ILSP1UniversalReceiver",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP1UniversalReceiver>;
    deployContract(
      name: "LSP4DigitalAssetMetadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP4DigitalAssetMetadata>;
    deployContract(
      name: "LSP4DigitalAssetMetadataCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP4DigitalAssetMetadataCore>;
    deployContract(
      name: "ILSP7DigitalAsset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP7DigitalAsset>;
    deployContract(
      name: "LSP7DigitalAsset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP7DigitalAsset>;
    deployContract(
      name: "LSP7DigitalAssetCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP7DigitalAssetCore>;
    deployContract(
      name: "ILSP8IdentifiableDigitalAsset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP8IdentifiableDigitalAsset>;
    deployContract(
      name: "LSP8IdentifiableDigitalAsset",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8IdentifiableDigitalAsset>;
    deployContract(
      name: "LSP8IdentifiableDigitalAssetCore",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8IdentifiableDigitalAssetCore>;
    deployContract(
      name: "ILSP8Mintable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ILSP8Mintable>;
    deployContract(
      name: "LSP8Mintable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8Mintable>;
    deployContract(
      name: "ERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC165>;
    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "BasicLSP8",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasicLSP8>;
    deployContract(
      name: "BasicLSP8CollectionOfCollections",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasicLSP8CollectionOfCollections>;
    deployContract(
      name: "LSP7SubCollection",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP7SubCollection>;
    deployContract(
      name: "LSP8Collection",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8Collection>;
    deployContract(
      name: "BasicLSP8Collection",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.BasicLSP8Collection>;
    deployContract(
      name: "LSP8Proxy",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LSP8Proxy>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
